# Generated by Django 4.2.4 on 2023-09-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_customgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
